classdef PreviewPanel < matlab.ui.internal.databrowser.AbstractDataBrowser
    %% PreviewPanel - Preview panel for cotrol system designer app
    %
    %  Note that this preview panel assume that
    %      - A data browser item provides GETDISPLAYPREVIEWTEXT function to
    %        generate a text-based description of the item.
    %      - An event data generated by a data browser must provide the 
    %        selected data index and external event names (as a cell array)
    %        that may externally change the data while it is selected for
    %        preview.
    
    % Copyright 2020 The MathWorks, Inc.
    
    %% Properties
    properties (SetAccess = private)
        TextArea
    end
    
    properties(Access=private)
        % Listener to listen to additional events that may change the
        % selected data.
        ValueChangedListener
    end
    
    %% Constructor
    methods
        function this = PreviewPanel(name, title)
            this = this@matlab.ui.internal.databrowser.AbstractDataBrowser(name, title);
            buildUI(this);
            connectUI(this);
        end        
    end
    
    %% public methods
    methods        
        function updateUI(this, txt)
            %% Update preview area.
            
            this.TextArea.Value = txt;
        end
        
        function monitor(this, databrowser)
            %% Add listener for preview request.
            weakThis = matlab.lang.WeakReference(this);
            lis = addlistener(databrowser,'PreviewRequested', ...
                @(src,event)DataBrowserSelectionChanged(weakThis.Handle,src,event));
            registerUIListeners(this, lis);
        end        
    end
    
    %% Protected methods
    methods(Access = protected)        
        function buildUI(this)
            %% Build preview area
            
            % Use 1x1 uigridlayout for auto-resizing
            g = uigridlayout(this.Figure);
            g.ColumnWidth = {'1x'};
            g.RowHeight = {'1x'};
            g.Padding = [0 0 0 0];
            
            % Add text area for preview.
            txt = uitextarea(g);
            txt.Editable = false;
            txt.FontName = 'Courier';
            txt.Tag = strcat('txtarea',this.Name);
            this.TextArea = txt;
        end
        
        function DataBrowserSelectionChanged(this,src,event)
            %% Display information of a selected item.
            
            resetValuChangedListener(this)
            %unregisterDataListeners(this)
            idx = event.Index;
            if isempty(idx)
                % No row is selected.
                str = '';                
            elseif isscalar(idx)
                % A single row is selected.
                val = getData(src,idx);
                
                % Register external events that may chage the data.
                if isempty(val) || ~isvalid(val)
                    str = '';
                    disp('Invalid value')
                else
                    weakThis = matlab.lang.WeakReference(this);
                    for i = 1:numel(event.ExternalEvents)
                        this.ValueChangedListener = [this.ValueChangedListener ...
                            addlistener(val,event.ExternalEvents{i}, ...
                            @(src,evt)updatePreview(weakThis.Handle,val))];
                    end
                    
                    % Get text description of the data.
                    str = getDisplayPreviewText(val);
                end                
            else
                str = '';
            end
            updateUI(this, str)
        end
        
        function cleanupUI(this)
            resetValuChangedListener(this)
        end
    end
    
    %% Private methods
    methods(Access=private)
        function updatePreview(this,val)
            %% Update preview of the specified data.
            
            str = getDisplayPreviewText(val);
            updateUI(this, str)
        end
        
        function resetValuChangedListener(this)
            %% Delete current value changed listener.
            
            if ~isempty(this.ValueChangedListener)
                delete(this.ValueChangedListener)
                this.ValueChangedListener = [];
            end
        end
    end
end