classdef (CaseInsensitiveProperties, TruncatedProperties,...
      InferiorClasses = {? matlab.graphics.axis.Axes,...
? matlab.ui.control.UIAxes,...
? matlab.ui.Figure,...
? matlab.ui.container.Panel,...
? matlab.ui.container.Tab,...
? matlab.ui.container.GridLayout,...
? matlab.graphics.layout.TiledChartLayout}) ...
      ss < tunableSS
   %LTIBLOCK.SS  See tunableSS.

   %   Copyright 2009-2015 The MathWorks, Inc.
   methods
      function blk = ss(varargin)
         blk@tunableSS(varargin{:});
      end
   end
end