classdef FuzzyControllerUI < ControllerUIBase
    % FUZZYCONTROLLERUI 模糊控制器UI
    
    properties
        name = '模糊控制器'
        description = '基于模糊逻辑的控制器设计'
        controller_type = 'Fuzzy'
    end
    
    methods
        function obj = FuzzyControllerUI(parent_panel, app_handle)
            % 构造函数
            obj = obj@ControllerUIBase(parent_panel, app_handle);
            if exist('fis', 'file')
                obj.controller = FuzzyController();
            else
                warndlg('需要Fuzzy Logic Toolbox', '工具箱缺失');
            end
        end
        
        function createUI(obj)
            % 创建模糊控制器UI
            obj.controls.panel = uipanel('Parent', obj.parent_panel, ...
                'Title', '模糊控制器设计', ...
                'Position', [0, 0, 1, 1], ...
                'BackgroundColor', [0.96, 0.96, 0.96], ...
                'Visible', 'off');
            
            % 检查工具箱
            if ~exist('fis', 'file')
                uicontrol('Parent', obj.controls.panel, ...
                    'Style', 'text', ...
                    'String', '需要Fuzzy Logic Toolbox', ...
                    'Position', [0.3, 0.4, 0.4, 0.2], ...
                    'FontSize', 14, ...
                    'ForegroundColor', 'red', ...
                    'BackgroundColor', [0.96, 0.96, 0.96]);
                return;
            end
            
            % 设计参数面板
            design_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计参数', ...
                'Position', [0.01, 0.85, 0.98, 0.14], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 输入变量
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '输入变量:', ...
                'Position', [20, 30, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92], ...
                'FontWeight', 'bold');
            
            obj.controls.inputs = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '误差,误差变化率', ...
                'Position', [90, 30, 150, 25], ...
                'BackgroundColor', 'white');
            
            % 输出变量
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '输出变量:', ...
                'Position', [260, 30, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.outputs = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '控制信号', ...
                'Position', [330, 30, 100, 25], ...
                'BackgroundColor', 'white');
            
            % 隶属函数类型
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '隶属函数:', ...
                'Position', [20, 5, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.mf_type = uicontrol('Parent', design_panel, ...
                'Style', 'popupmenu', ...
                'String', {'三角形', '高斯型', '钟形', '梯形'}, ...
                'Value', 1, ...
                'Position', [90, 5, 100, 25], ...
                'BackgroundColor', 'white');
            
            % 规则数
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '规则数量:', ...
                'Position', [210, 5, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.num_rules = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '9', ...
                'Position', [280, 5, 50, 25], ...
                'BackgroundColor', 'white');
            
            % 控制按钮
            obj.controls.design = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '设计控制器', ...
                'Position', [360, 15, 100, 35], ...
                'BackgroundColor', [0.2, 0.5, 0.8], ...
                'ForegroundColor', 'white', ...
                'FontWeight', 'bold', ...
                'Callback', @(~,~) obj.designController());
            
            obj.controls.simulate = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '仿真', ...
                'Position', [470, 15, 80, 35], ...
                'BackgroundColor', [0.3, 0.7, 0.3], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.simulateControl());
            
            obj.controls.export = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '导出', ...
                'Position', [560, 15, 80, 35], ...
                'BackgroundColor', [0.8, 0.5, 0.2], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.exportController());
            
            % 信息文本
            obj.controls.info_text = uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '请先加载系统模型', ...
                'Position', [650, 20, 200, 30], ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 结果显示区域
            results_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计结果', ...
                'Position', [0.01, 0.01, 0.98, 0.83], ...
                'BackgroundColor', 'white');
            
            % 创建绘图坐标轴
            obj.createAxes(results_panel);
        end
        
        function createAxes(obj, parent)
            % 创建绘图坐标轴
            obj.controls.axes_handles = zeros(2, 2);
            
            for i = 1:2
                for j = 1:2
                    idx = (i-1)*2 + j;
                    obj.controls.axes_handles(i,j) = subplot(2,2,idx, 'Parent', parent);
                end
            end
        end
        
        function designController(obj)
            % 设计模糊控制器
            if isempty(obj.controller.plant_model)
                errordlg('请先设置系统模型', '错误');
                return;
            end
            
            if ~exist('fis', 'file')
                errordlg('需要Fuzzy Logic Toolbox', '错误');
                return;
            end
            
            try
                % 获取设计参数
                inputs_str = get(obj.controls.inputs, 'String');
                outputs_str = get(obj.controls.outputs, 'String');
                mf_type_idx = get(obj.controls.mf_type, 'Value');
                mf_types = {'trimf', 'gaussmf', 'gbellmf', 'trapmf'};
                mf_type = mf_types{mf_type_idx};
                num_rules = str2double(get(obj.controls.num_rules, 'String'));
                
                if isnan(num_rules)
                    errordlg('请输入有效的规则数量', '错误');
                    return;
                end
                
                % 设置设计参数
                design_params = struct();
                design_params.inputs = strsplit(inputs_str, ',');
                design_params.outputs = strsplit(outputs_str, ',');
                design_params.mf_type = mf_type;
                design_params.num_rules = num_rules;
                
                obj.controller.setDesignParams(design_params);
                
                % 设计控制器
                obj.controller.design();
                
                % 更新UI
                obj.updateUI();
                
                msgbox('模糊控制器设计完成', '成功');
                
            catch ME
                errordlg(['设计失败: ', ME.message], '错误');
            end
        end
        
        function updateUI(obj)
            % 更新UI
            if ~isempty(obj.controller) && ~isempty(obj.controller.plant_model)
                % 如果有系统模型，更新信息
                [num, den] = tfdata(obj.controller.plant_model, 'v');
                sys_info = sprintf('系统模型: %d阶/%d阶', length(num)-1, length(den)-1);
                set(obj.controls.info_text, 'String', sys_info, 'ForegroundColor', 'green');
            else
                set(obj.controls.info_text, 'String', '请先设置系统模型', 'ForegroundColor', 'blue');
            end
        end
    end
end