classdef LQRControllerUI < ControllerUIBase
    % LQRCONTROLLERUI LQR最优控制UI
    
    properties
        name = 'LQR最优控制'
        description = '线性二次型调节器设计'
        controller_type = 'LQR'
    end
    
    methods
        function obj = LQRControllerUI(parent_panel, app_handle)
            % 构造函数
            obj = obj@ControllerUIBase(parent_panel, app_handle);
            obj.controller = LQRController();
        end
        
        function createUI(obj)
            % 创建LQR控制器UI
            obj.controls.panel = uipanel('Parent', obj.parent_panel, ...
                'Title', 'LQR最优控制设计', ...
                'Position', [0, 0, 1, 1], ...
                'BackgroundColor', [0.96, 0.96, 0.96], ...
                'Visible', 'off');
            
            % 设计参数面板
            design_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计参数', ...
                'Position', [0.01, 0.85, 0.98, 0.14], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % Q矩阵对角元素
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '状态权重Q:', ...
                'Position', [20, 30, 80, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92], ...
                'FontWeight', 'bold');
            
            obj.controls.q_diagonal = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '1, 1, 1', ...
                'Position', [100, 30, 120, 25], ...
                'BackgroundColor', 'white');
            
            % R矩阵对角元素
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '控制权重R:', ...
                'Position', [240, 30, 80, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.r_diagonal = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '0.1', ...
                'Position', [320, 30, 80, 25], ...
                'BackgroundColor', 'white');
            
            % 积分器
            obj.controls.integrator = uicontrol('Parent', design_panel, ...
                'Style', 'checkbox', ...
                'String', '添加积分器', ...
                'Value', 1, ...
                'Position', [20, 5, 100, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 观测器类型
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '观测器:', ...
                'Position', [140, 5, 60, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.observer_type = uicontrol('Parent', design_panel, ...
                'Style', 'popupmenu', ...
                'String', {'无', 'Luenberger', 'Kalman'}, ...
                'Value', 1, ...
                'Position', [200, 5, 100, 25], ...
                'BackgroundColor', 'white');
            
            % 极点位置（用于Luenberger观测器）
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '观测器极点:', ...
                'Position', [320, 5, 80, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.observer_poles = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '-2, -3', ...
                'Position', [400, 5, 80, 25], ...
                'BackgroundColor', 'white');
            
            % 控制按钮
            obj.controls.design = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '设计控制器', ...
                'Position', [500, 15, 100, 35], ...
                'BackgroundColor', [0.2, 0.5, 0.8], ...
                'ForegroundColor', 'white', ...
                'FontWeight', 'bold', ...
                'Callback', @(~,~) obj.designController());
            
            obj.controls.simulate = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '仿真', ...
                'Position', [610, 15, 80, 35], ...
                'BackgroundColor', [0.3, 0.7, 0.3], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.simulateControl());
            
            obj.controls.export = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '导出', ...
                'Position', [700, 15, 80, 35], ...
                'BackgroundColor', [0.8, 0.5, 0.2], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.exportController());
            
            % 信息文本
            obj.controls.info_text = uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '请先加载系统模型', ...
                'Position', [790, 20, 200, 30], ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 结果显示区域
            results_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计结果', ...
                'Position', [0.01, 0.01, 0.98, 0.83], ...
                'BackgroundColor', 'white');
            
            % 创建绘图坐标轴
            obj.createAxes(results_panel);
        end
        
        function createAxes(obj, parent)
            % 创建绘图坐标轴
            obj.controls.axes_handles = zeros(2, 2);
            
            for i = 1:2
                for j = 1:2
                    idx = (i-1)*2 + j;
                    obj.controls.axes_handles(i,j) = subplot(2,2,idx, 'Parent', parent);
                end
            end
        end
        
        function designController(obj)
            % 设计LQR控制器
            if isempty(obj.controller.plant_model)
                errordlg('请先设置系统模型', '错误');
                return;
            end
            
            try
                % 获取设计参数
                q_str = get(obj.controls.q_diagonal, 'String');
                r_str = get(obj.controls.r_diagonal, 'String');
                integrator = get(obj.controls.integrator, 'Value');
                observer_idx = get(obj.controls.observer_type, 'Value');
                observer_types = {'none', 'luenberger', 'kalman'};
                observer_type = observer_types{observer_idx};
                observer_poles_str = get(obj.controls.observer_poles, 'String');
                
                % 解析Q和R矩阵
                q_vals = str2num(q_str); %#ok<ST2NM>
                r_vals = str2num(r_str); %#ok<ST2NM>
                observer_poles = str2num(observer_poles_str); %#ok<ST2NM>
                
                if isempty(q_vals) || isempty(r_vals)
                    errordlg('请输入有效的权重矩阵', '错误');
                    return;
                end
                
                % 设置设计参数
                design_params = struct();
                design_params.Q = diag(q_vals);
                design_params.R = diag(r_vals);
                design_params.integrator = integrator;
                design_params.observer_type = observer_type;
                if strcmp(observer_type, 'luenberger')
                    design_params.observer_poles = observer_poles;
                end
                
                obj.controller.setDesignParams(design_params);
                
                % 设计控制器
                obj.controller.design();
                
                % 更新UI
                obj.updateUI();
                
                msgbox('LQR控制器设计完成', '成功');
                
            catch ME
                errordlg(['设计失败: ', ME.message], '错误');
            end
        end
        
        function updateUI(obj)
            % 更新UI
            if ~isempty(obj.controller) && ~isempty(obj.controller.plant_model)
                % 如果有系统模型，更新信息
                [num, den] = tfdata(obj.controller.plant_model, 'v');
                sys_info = sprintf('系统模型: %d阶/%d阶', length(num)-1, length(den)-1);
                set(obj.controls.info_text, 'String', sys_info, 'ForegroundColor', 'green');
            else
                set(obj.controls.info_text, 'String', '请先设置系统模型', 'ForegroundColor', 'blue');
            end
        end
    end
end