classdef MPCControllerUI < ControllerUIBase
    % MPCCONTROLLERUI 模型预测控制UI
    
    properties
        name = '模型预测控制'
        description = '基于模型预测的控制器设计'
        controller_type = 'MPC'
    end
    
    methods
        function obj = MPCControllerUI(parent_panel, app_handle)
            % 构造函数
            if nargin < 2
                error('MPCControllerUI需要两个参数：parent_panel和app_handle');
            end
            obj = obj@ControllerUIBase(parent_panel, app_handle);
            if exist('mpc', 'file')
                obj.controller = MPCController();
            else
                warndlg('需要MPC Toolbox', '工具箱缺失');
            end
        end
        
        function createUI(obj)
            % 创建MPC控制器UI
            obj.controls.panel = uipanel('Parent', obj.parent_panel, ...
                'Title', '模型预测控制设计', ...
                'Position', [0, 0, 1, 1], ...
                'BackgroundColor', [0.96, 0.96, 0.96], ...
                'Visible', 'off');
            
            % 检查工具箱
            if ~exist('mpc', 'file')
                uicontrol('Parent', obj.controls.panel, ...
                    'Style', 'text', ...
                    'String', '需要MPC Toolbox', ...
                    'Position', [0.3, 0.4, 0.4, 0.2], ...
                    'FontSize', 14, ...
                    'ForegroundColor', 'red', ...
                    'BackgroundColor', [0.96, 0.96, 0.96]);
                return;
            end
            
            % 设计参数面板
            design_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计参数', ...
                'Position', [0.01, 0.85, 0.98, 0.14], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 预测时域
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '预测时域:', ...
                'Position', [20, 30, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92], ...
                'FontWeight', 'bold');
            
            obj.controls.prediction_horizon = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '10', ...
                'Position', [90, 30, 60, 25], ...
                'BackgroundColor', 'white');
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '步', ...
                'Position', [155, 30, 20, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 控制时域
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '控制时域:', ...
                'Position', [190, 30, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.control_horizon = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '3', ...
                'Position', [260, 30, 60, 25], ...
                'BackgroundColor', 'white');
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '步', ...
                'Position', [325, 30, 20, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 采样时间
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '采样时间:', ...
                'Position', [20, 5, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.sample_time = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '0.1', ...
                'Position', [90, 5, 60, 25], ...
                'BackgroundColor', 'white');
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', 's', ...
                'Position', [155, 5, 20, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 权重矩阵
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '输出权重:', ...
                'Position', [190, 5, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.output_weight = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '1.0', ...
                'Position', [260, 5, 60, 25], ...
                'BackgroundColor', 'white');
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '控制权重:', ...
                'Position', [340, 5, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.control_weight = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '0.1', ...
                'Position', [410, 5, 60, 25], ...
                'BackgroundColor', 'white');
            
            % 控制按钮
            obj.controls.design = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '设计控制器', ...
                'Position', [500, 15, 100, 35], ...
                'BackgroundColor', [0.2, 0.5, 0.8], ...
                'ForegroundColor', 'white', ...
                'FontWeight', 'bold', ...
                'Callback', @(~,~) obj.designController());
            
            obj.controls.simulate = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '仿真', ...
                'Position', [610, 15, 80, 35], ...
                'BackgroundColor', [0.3, 0.7, 0.3], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.simulateControl());
            
            obj.controls.export = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '导出', ...
                'Position', [700, 15, 80, 35], ...
                'BackgroundColor', [0.8, 0.5, 0.2], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.exportController());
            
            % 信息文本
            obj.controls.info_text = uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '请先加载系统模型', ...
                'Position', [790, 20, 200, 30], ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 结果显示区域
            results_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计结果', ...
                'Position', [0.01, 0.01, 0.98, 0.83], ...
                'BackgroundColor', 'white');
            
            % 创建绘图坐标轴
            obj.createAxes(results_panel);
        end
        
        function createAxes(obj, parent)
            % 创建绘图坐标轴
            obj.controls.axes_handles = cell(2, 2);
            
            for i = 1:2
                for j = 1:2
                    idx = (i-1)*2 + j;
                    obj.controls.axes_handles{i,j} = subplot(2,2,idx, 'Parent', parent);
                end
            end
        end
        
        function designController(obj)
            % 设计MPC控制器
            if isempty(obj.controller.plant_model)
                errordlg('请先设置系统模型', '错误');
                return;
            end
            
            if ~exist('mpc', 'file')
                errordlg('需要MPC Toolbox', '错误');
                return;
            end
            
            try
                % 获取设计参数
                prediction_horizon = str2double(get(obj.controls.prediction_horizon, 'String'));
                control_horizon = str2double(get(obj.controls.control_horizon, 'String'));
                sample_time = str2double(get(obj.controls.sample_time, 'String'));
                output_weight = str2double(get(obj.controls.output_weight, 'String'));
                control_weight = str2double(get(obj.controls.control_weight, 'String'));
                
                if any(isnan([prediction_horizon, control_horizon, sample_time, output_weight, control_weight]))
                    errordlg('请输入有效的设计参数', '错误');
                    return;
                end
                
                % 设置设计参数
                design_params = struct();
                design_params.prediction_horizon = prediction_horizon;
                design_params.control_horizon = control_horizon;
                design_params.sample_time = sample_time;
                design_params.output_weight = output_weight;
                design_params.control_weight = control_weight;
                
                obj.controller.setDesignParams(design_params);
                
                % 设计控制器
                obj.controller.design();
                
                % 更新UI
                obj.updateUI();
                
                msgbox('MPC控制器设计完成', '成功');
                
            catch ME
                errordlg(['设计失败: ', ME.message], '错误');
            end
        end
        
        function updateUI(obj)
            % 调用父类的通用更新
            updateUI@ControllerUIBase(obj);
            
            % 子类特定的更新：MPC参数显示可以在这里添加
        end
    end
end