classdef PIDControllerUI < ControllerUIBase
    % PIDCONTROLLERUI PID控制器UI
    
    properties
        name = 'PID控制器'
        description = '比例-积分-微分控制器设计'
        controller_type = 'PID'
    end
    
    methods
        function obj = PIDControllerUI(parent_panel, app_handle)
            % 构造函数
            obj = obj@ControllerUIBase(parent_panel, app_handle);
            obj.controller = PIDController();
        end
        
        function createUI(obj)
            % 创建PID控制器UI
            obj.controls.panel = uipanel('Parent', obj.parent_panel, ...
                'Title', 'PID控制器设计', ...
                'Position', [0, 0, 1, 1], ...
                'BackgroundColor', [0.96, 0.96, 0.96], ...
                'Visible', 'off');
            
            % 设计参数面板
            design_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计参数', ...
                'Position', [0.01, 0.85, 0.98, 0.14], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 设计方法选择
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '设计方法:', ...
                'Position', [20, 30, 70, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92], ...
                'FontWeight', 'bold');
            
            obj.controls.method = uicontrol('Parent', design_panel, ...
                'Style', 'popupmenu', ...
                'String', {'Ziegler-Nichols', 'Cohen-Coon', 'IMC', 'ITAE最优', '手动调节', '自动整定', '频域设计'}, ...
                'Value', 1, ...
                'Position', [90, 30, 120, 25], ...
                'BackgroundColor', 'white', ...
                'Callback', @(~,~) obj.onMethodChanged());
            
            % PID类型选择
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', 'PID类型:', ...
                'Position', [230, 30, 60, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.pid_type = uicontrol('Parent', design_panel, ...
                'Style', 'popupmenu', ...
                'String', {'PID', 'PI', 'P'}, ...
                'Value', 1, ...
                'Position', [290, 30, 60, 25], ...
                'BackgroundColor', 'white');
            
            % 性能指标
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '上升时间:', ...
                'Position', [20, 5, 60, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.rise_time = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '1.0', ...
                'Position', [80, 5, 60, 25], ...
                'BackgroundColor', 'white');
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', 's', ...
                'Position', [145, 5, 20, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '超调量:', ...
                'Position', [170, 5, 60, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            obj.controls.overshoot = uicontrol('Parent', design_panel, ...
                'Style', 'edit', ...
                'String', '5.0', ...
                'Position', [230, 5, 60, 25], ...
                'BackgroundColor', 'white');
            
            uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '%', ...
                'Position', [295, 5, 20, 20], ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 控制按钮
            obj.controls.design = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '设计控制器', ...
                'Position', [360, 15, 100, 35], ...
                'BackgroundColor', [0.2, 0.5, 0.8], ...
                'ForegroundColor', 'white', ...
                'FontWeight', 'bold', ...
                'Callback', @(~,~) obj.designController());
            
            obj.controls.simulate = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '仿真', ...
                'Position', [470, 15, 80, 35], ...
                'BackgroundColor', [0.3, 0.7, 0.3], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.simulateControl());
            
            obj.controls.export = uicontrol('Parent', design_panel, ...
                'Style', 'pushbutton', ...
                'String', '导出', ...
                'Position', [560, 15, 80, 35], ...
                'BackgroundColor', [0.8, 0.5, 0.2], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.exportController());
            
            % 手动调节面板
            obj.createManualTuningPanel(design_panel);
            
            % 信息文本
            obj.controls.info_text = uicontrol('Parent', design_panel, ...
                'Style', 'text', ...
                'String', '请先加载系统模型', ...
                'Position', [650, 20, 200, 30], ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', [0.92, 0.92, 0.92]);
            
            % 结果显示区域
            results_panel = uipanel('Parent', obj.controls.panel, ...
                'Title', '设计结果', ...
                'Position', [0.01, 0.01, 0.98, 0.83], ...
                'BackgroundColor', 'white');
            
            % 创建绘图坐标轴
            obj.createAxes(results_panel);
        end
        
        function createManualTuningPanel(obj, parent)
            % 创建手动调节面板
            tuning_panel = uipanel('Parent', parent, ...
                'Title', '手动调节参数', ...
                'Position', [0.01, -0.25, 0.98, 0.35], ...
                'BackgroundColor', [0.95, 0.95, 0.95], ...
                'Visible', 'off');
            
            obj.controls.tuning_panel = tuning_panel;
            
            % Kp调节
            uicontrol('Parent', tuning_panel, ...
                'Style', 'text', 'String', 'Kp:', ...
                'Position', [20, 40, 30, 20], ...
                'BackgroundColor', [0.95, 0.95, 0.95]);
            
            obj.controls.kp_edit = uicontrol('Parent', tuning_panel, ...
                'Style', 'edit', ...
                'String', '1.0', ...
                'Position', [50, 40, 60, 25], ...
                'BackgroundColor', 'white', ...
                'Callback', @(~,~) obj.updateControllerParams());
            
            obj.controls.kp_slider = uicontrol('Parent', tuning_panel, ...
                'Style', 'slider', ...
                'Min', 0, 'Max', 10, 'Value', 1.0, ...
                'Position', [120, 40, 100, 25], ...
                'Callback', @(~,~) obj.onKpSliderChanged());
            
            % Ki调节
            uicontrol('Parent', tuning_panel, ...
                'Style', 'text', 'String', 'Ki:', ...
                'Position', [20, 10, 30, 20], ...
                'BackgroundColor', [0.95, 0.95, 0.95]);
            
            obj.controls.ki_edit = uicontrol('Parent', tuning_panel, ...
                'Style', 'edit', ...
                'String', '0.1', ...
                'Position', [50, 10, 60, 25], ...
                'BackgroundColor', 'white', ...
                'Callback', @(~,~) obj.updateControllerParams());
            
            obj.controls.ki_slider = uicontrol('Parent', tuning_panel, ...
                'Style', 'slider', ...
                'Min', 0, 'Max', 5, 'Value', 0.1, ...
                'Position', [120, 10, 100, 25], ...
                'Callback', @(~,~) obj.onKiSliderChanged());
            
            % Kd调节
            uicontrol('Parent', tuning_panel, ...
                'Style', 'text', 'String', 'Kd:', ...
                'Position', [240, 40, 30, 20], ...
                'BackgroundColor', [0.95, 0.95, 0.95]);
            
            obj.controls.kd_edit = uicontrol('Parent', tuning_panel, ...
                'Style', 'edit', ...
                'String', '0.01', ...
                'Position', [270, 40, 60, 25], ...
                'BackgroundColor', 'white', ...
                'Callback', @(~,~) obj.updateControllerParams());
            
            obj.controls.kd_slider = uicontrol('Parent', tuning_panel, ...
                'Style', 'slider', ...
                'Min', 0, 'Max', 1, 'Value', 0.01, ...
                'Position', [340, 40, 100, 25], ...
                'Callback', @(~,~) obj.onKdSliderChanged());
            
            % 实时仿真按钮
            obj.controls.real_time_sim = uicontrol('Parent', tuning_panel, ...
                'Style', 'pushbutton', ...
                'String', '实时仿真', ...
                'Position', [460, 25, 80, 30], ...
                'BackgroundColor', [0.4, 0.8, 0.4], ...
                'ForegroundColor', 'white', ...
                'Callback', @(~,~) obj.realTimeSimulate());
        end
        
        function createAxes(obj, parent)
            % 创建绘图坐标轴
            obj.controls.axes_handles = zeros(2, 2);
            
            for i = 1:2
                for j = 1:2
                    idx = (i-1)*2 + j;
                    obj.controls.axes_handles(i,j) = subplot(2,2,idx, 'Parent', parent);
                end
            end
        end
        
        function onMethodChanged(obj)
            % 设计方法改变回调
            method_idx = get(obj.controls.method, 'Value');
            methods = {'ziegler_nichols', 'cohen_coon', 'imc', 'itae', 'manual', 'auto_tune', 'frequency'};
            
            if strcmp(methods{method_idx}, 'manual')
                set(obj.controls.tuning_panel, 'Visible', 'on');
                obj.updateManualTuningParams();
            else
                set(obj.controls.tuning_panel, 'Visible', 'off');
            end
        end
        
        function updateManualTuningParams(obj)
            % 更新手动调节参数显示
            if isempty(obj.controller) || isempty(obj.controller.design_params)
                return;
            end
            
            params = obj.controller.design_params;
            
            if isfield(params, 'Kp')
                set(obj.controls.kp_edit, 'String', num2str(params.Kp));
                set(obj.controls.kp_slider, 'Value', params.Kp);
            end
            
            if isfield(params, 'Ki')
                set(obj.controls.ki_edit, 'String', num2str(params.Ki));
                set(obj.controls.ki_slider, 'Value', params.Ki);
            end
            
            if isfield(params, 'Kd')
                set(obj.controls.kd_edit, 'String', num2str(params.Kd));
                set(obj.controls.kd_slider, 'Value', params.Kd);
            end
        end
        
        function onKpSliderChanged(obj)
            % Kp滑块改变回调
            value = get(obj.controls.kp_slider, 'Value');
            set(obj.controls.kp_edit, 'String', num2str(value));
            obj.updateControllerParams();
        end
        
        function onKiSliderChanged(obj)
            % Ki滑块改变回调
            value = get(obj.controls.ki_slider, 'Value');
            set(obj.controls.ki_edit, 'String', num2str(value));
            obj.updateControllerParams();
        end
        
        function onKdSliderChanged(obj)
            % Kd滑块改变回调
            value = get(obj.controls.kd_slider, 'Value');
            set(obj.controls.kd_edit, 'String', num2str(value));
            obj.updateControllerParams();
        end
        
        function updateControllerParams(obj)
            % 更新控制器参数
            try
                Kp = str2double(get(obj.controls.kp_edit, 'String'));
                Ki = str2double(get(obj.controls.ki_edit, 'String'));
                Kd = str2double(get(obj.controls.kd_edit, 'String'));
                
                if isnan(Kp) || isnan(Ki) || isnan(Kd)
                    return;
                end
                
                obj.controller.design_params.Kp = Kp;
                obj.controller.design_params.Ki = Ki;
                obj.controller.design_params.Kd = Kd;
                
                % 重新设计控制器
                obj.controller.design();
                
            catch ME
                disp(['参数更新错误: ', ME.message]);
            end
        end
        
        function realTimeSimulate(obj)
            % 实时仿真
            obj.simulateControl();
        end
        
        function designController(obj)
            % 设计PID控制器
            if isempty(obj.controller.plant_model)
                errordlg('请先设置系统模型', '错误');
                return;
            end
            
            try
                % 获取设计参数
                method_idx = get(obj.controls.method, 'Value');
                methods = {'ziegler_nichols', 'cohen_coon', 'imc', 'itae', 'manual', 'auto_tune', 'frequency'};
                method = methods{method_idx};
                
                pid_type_idx = get(obj.controls.pid_type, 'Value');
                pid_types = {'PID', 'PI', 'P'};
                pid_type = pid_types{pid_type_idx};
                
                rise_time = str2double(get(obj.controls.rise_time, 'String'));
                overshoot = str2double(get(obj.controls.overshoot, 'String'));
                
                if isnan(rise_time) || isnan(overshoot)
                    errordlg('请输入有效的性能指标', '错误');
                    return;
                end
                
                % 设置设计参数
                design_params = struct();
                design_params.method = method;
                design_params.pid_type = pid_type;
                design_params.rise_time = rise_time;
                design_params.overshoot = overshoot;
                
                if strcmp(method, 'manual')
                    design_params.Kp = str2double(get(obj.controls.kp_edit, 'String'));
                    design_params.Ki = str2double(get(obj.controls.ki_edit, 'String'));
                    design_params.Kd = str2double(get(obj.controls.kd_edit, 'String'));
                end
                
                obj.controller.setDesignParams(design_params);
                
                % 设计控制器
                obj.controller.design();
                
                % 更新UI
                obj.updateUI();
                
                msgbox('PID控制器设计完成', '成功');
                
            catch ME
                errordlg(['设计失败: ', ME.message], '错误');
            end
        end
        
        function updateUI(obj)
            % 更新UI
            if ~isempty(obj.controller) && ~isempty(obj.controller.plant_model)
                % 如果有系统模型，更新信息
                [num, den] = tfdata(obj.controller.plant_model, 'v');
                sys_info = sprintf('系统模型: %d阶/%d阶', length(num)-1, length(den)-1);
                set(obj.controls.info_text, 'String', sys_info, 'ForegroundColor', 'green');
            else
                set(obj.controls.info_text, 'String', '请先设置系统模型', 'ForegroundColor', 'blue');
            end
            
            % 显示控制器参数
            if ~isempty(obj.controller.design_params)
                params = obj.controller.design_params;
                if isfield(params, 'Kp')
                    set(obj.controls.kp_edit, 'String', num2str(params.Kp));
                    set(obj.controls.kp_slider, 'Value', params.Kp);
                end
                if isfield(params, 'Ki')
                    set(obj.controls.ki_edit, 'String', num2str(params.Ki));
                    set(obj.controls.ki_slider, 'Value', params.Ki);
                end
                if isfield(params, 'Kd')
                    set(obj.controls.kd_edit, 'String', num2str(params.Kd));
                    set(obj.controls.kd_slider, 'Value', params.Kd);
                end
            end
        end
    end
end