classdef (CaseInsensitiveProperties, TruncatedProperties,...
      InferiorClasses = {? matlab.graphics.axis.Axes,...
? matlab.ui.control.UIAxes,...
? matlab.ui.Figure,...
? matlab.ui.container.Panel,...
? matlab.ui.container.Tab,...
? matlab.ui.container.GridLayout,...
? matlab.graphics.layout.TiledChartLayout}) ...
      gain < tunableGain
   %LTIBLOCK.GAIN  See tunableGain.
   
   %   Copyright 1986-2015 The MathWorks
   methods
      function blk = gain(varargin)
         blk@tunableGain(varargin{:});
      end
   end
   
end