function sys = dynamicsys(varargin)
%DYNAMICSYS  Constructor for "dynamic system" parent object.
%
%   SYS = DYNAMICSYS(NY,NU) creates a dynamical system object with 
%   NY outputs and NU inputs.

%   Copyright 1986-2011 The MathWorks, Inc.

% sys = struct(...
%    'InputName',{EmptyStr(ones(Nu,1),:)},...
%    'OutputName',{EmptyStr(ones(Ny,1),:)},...
%    'InputGroup',struct,...
%    'OutputGroup',struct,...
%    'Name','',...
%    'Notes',{{}},...
%    'UserData',[],...
%    'Version',ltipack.ver(),...
%    'VersionData',[]);  % used to support upgrade from pre-R14;
sys = class(struct,'dynamicsys');
