classdef (CaseInsensitiveProperties, TruncatedProperties,...
      InferiorClasses = {? matlab.graphics.axis.Axes,...
? matlab.ui.control.UIAxes,...
? matlab.ui.Figure,...
? matlab.ui.container.Panel,...
? matlab.ui.container.Tab,...
? matlab.ui.container.GridLayout,...
? matlab.graphics.layout.TiledChartLayout}) ...
      tf < tunableTF
   %LTIBLOCK.TF  See tunableTF.

   %   Copyright 2009-2015 The MathWorks, Inc.
   methods
      function blk = tf(varargin)
         blk@tunableTF(varargin{:});
      end
   end
end