function DisplayText = createDisplayTuningGoal(this)
% Utility function for display text of Tuning Goal.

% Copyright 2013 The MathWorks, Inc.

Type = systuneapp.util.getTuningGoalType(this);

DisplayText = '';
% Type and Name Information
DisplayText = [ ...
    systuneapp.util.createDisplayText('type', ...
    getString(message(['Control:systunegui:Display' Type]))), ...
    systuneapp.util.createDisplayText('line', ...
    getString(message('Control:systunegui:DisplayName')),this.Name)];

% Information of IOs or Loop or Others
switch Type
    case {'Tracking','Overshoot','Gain','WeightedGain', ...
            'Variance','WeightedVariance','StepResp','StepRejection','Transient','LQG','Passivity','ConicSector','WeightedPassivity'} % IOs
        % Inputs
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayInput')),this.Input)];
        % Outputs
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayOutput')),this.Output)];        
        % If exist, Openings
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayOpening')),this.Openings)];
        switch Type
            case 'Tracking'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayMaxError')), ...
                    systuneapp.util.createDisplayTF(this.MaxError))];
            case 'Overshoot'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('line', ...
                        getString(message('Control:systunegui:DisplayMaxOvershoot')), ...
                        systuneapp.util.createDisplayTF(this.MaxOvershoot))];
            case 'Gain'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayMaxGain')), ...
                    systuneapp.util.createDisplayTF(this.MaxGain))];
            case 'ConicSector'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayConicSectorMatrix')), ...
                    systuneapp.util.createDisplayConicSectorMatrix(this.Q))];
            case 'Passivity'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayIPX')), ...
                    systuneapp.util.createDisplayTF(this.IPX)),...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayOPX')), ...
                    systuneapp.util.createDisplayTF(this.OPX))];
            case 'WeightedPassivity'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayWL')), ...
                    systuneapp.util.createDisplayTF(this.WL)), ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayWR')), ...
                    systuneapp.util.createDisplayTF(this.WR)), ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayIPX')), ...
                    systuneapp.util.createDisplayTF(this.IPX)),...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayOPX')), ...
                    systuneapp.util.createDisplayTF(this.OPX))];
            case {'WeightedGain','WeightedVariance'}
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayWL')), ...
                        systuneapp.util.createDisplayTF(this.WL)), ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayWR')), ...
                        systuneapp.util.createDisplayTF(this.WR)), ...                        
                              ];                   
            case 'Variance'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('line', ...
                        getString(message('Control:systunegui:DisplayMaxAmplification')), ...
                        systuneapp.util.createDisplayTF(this.MaxAmplification))];                
            case {'StepResp','StepRejection','Transient'}
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                    getString(message('Control:systunegui:DisplayReferenceModel')), ...
                    systuneapp.util.createDisplayTF(this.ReferenceModel))];               
            case 'LQG'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayNoiseCovariance')), ...
                        systuneapp.util.createDisplayMatrix(this.NoiseCovariance)), ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayPerformanceWeight')), ...
                        systuneapp.util.createDisplayMatrix(this.PerformanceWeight)), ...                        
                              ];                 
        end
        % If exist, Models
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('line', ...
            getString(message('Control:systunegui:DisplayModel')),this.Model)];        
    case {'MinLoopGain','MaxLoopGain','LoopShape', ...
            'Sensitivity','Margins','Poles'} % Loop
        % Locations
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayLocation')),this.Location)];
        % If exist, Openings
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayOpening')),this.Openings)];
        switch Type
            case 'MinLoopGain'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayMinLoopGain')), ...
                        systuneapp.util.createDisplayTF(this.MinGain))];             
            case 'MaxLoopGain'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayMaxLoopGain')), ...
                        systuneapp.util.createDisplayTF(this.MaxGain))];                                     
            case 'LoopShape'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayLoopGain')), ...
                        systuneapp.util.createDisplayTF(this.LoopGain))];      
            case 'Sensitivity'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('section', ...
                        getString(message('Control:systunegui:DisplayMaxSensitivity')), ...
                        systuneapp.util.createDisplayTF(this.MaxSensitivity))];       
            case 'Margins'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('line', ...
                        getString(message('Control:systunegui:DisplayGainMargin')), ...
                        systuneapp.util.createDisplayTF(this.GainMargin)), ...
                    systuneapp.util.createDisplayText('line', ...
                        getString(message('Control:systunegui:DisplayPhaseMargin')), ...
                        systuneapp.util.createDisplayTF(this.PhaseMargin)), ...
                    ];   
            case 'Poles'
                DisplayText = [DisplayText, ...
                    systuneapp.util.createDisplayText('line', ...
                        getString(message('Control:systunegui:DisplayMinDecay')), ...
                        systuneapp.util.createDisplayTF(this.MinDecay)), ...
                    systuneapp.util.createDisplayText('line', ...
                        getString(message('Control:systunegui:DisplayMinDamping')), ...
                        systuneapp.util.createDisplayTF(this.MinDamping)), ...
                    systuneapp.util.createDisplayText('line', ...                        
                        getString(message('Control:systunegui:DisplayMaxFrequency')), ...
                        systuneapp.util.createDisplayMatrix(this.MaxFrequency)), ...                    
                    ];                  
        end
        % If exist, Models
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('line', ...
                getString(message('Control:systunegui:DisplayModel')),this.Model)];                
    case 'Rejection'
        % DisturbanceInput
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayDisturbanceInput')),this.DisturbanceInput)];   
        % If exist, Openings
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
            getString(message('Control:systunegui:DisplayOpening')),this.Openings)];        
        % Minimum Attenuation
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('section', ...
                getString(message('Control:systunegui:DisplayMinAttenuation')), ...
                systuneapp.util.createDisplayTF(this.MinAttenuation))];
        % If exist, Models
        DisplayText = [DisplayText, ...
                systuneapp.util.createDisplayText('line', ...
                getString(message('Control:systunegui:DisplayModel')),this.Model)];
    case 'StableController'
        % DisturbanceInput, MinDecay, MaxFrequency
        DisplayText = [DisplayText, ...
            systuneapp.util.createDisplayText('line', ...
                getString(message('Control:systunegui:DisplayBlock')),this.Block), ...
            systuneapp.util.createDisplayText('line', ...
                getString(message('Control:systunegui:DisplayMinDecay')), ...
                systuneapp.util.createDisplayTF(this.MinDecay)), ...
            systuneapp.util.createDisplayText('line', ...
                getString(message('Control:systunegui:DisplayMinDamping')), ...
                systuneapp.util.createDisplayTF(this.MinDamping)), ...                
            systuneapp.util.createDisplayText('line', ...
                getString(message('Control:systunegui:DisplayMaxFrequency')), ...
                systuneapp.util.createDisplayTF(this.MaxFrequency)), ...
                      ];
end
