function List = getTuningGoalName(GroupName)
% Utility function returning tuning goal list 
% groupnames:
%   time
%   frequency
%   openloop
%   passivity
%   systemdynamics
%   all or empty

% Copyright 2013 The MathWorks, Inc.

if nargin==0 || isempty(GroupName)
    GroupName = '';
end

QuickStart =  ...
    { ... 
    'Looptune'; ...
    };

TimeDomainRequirements =  ...
    { ... 
    'StepResp'; ...
    'StepRejection'; ...
    'Transient'; ...
    'LQG' ...
    };
        
FrequencyDomainRequirements = ...
    { ...
    'Gain'; ...
    'Variance'; ...
    'Tracking'; ...
    'Overshoot'; ...    
    'Rejection'; ...
    'Sensitivity'; ...
    'WeightedGain'; ...
    'WeightedVariance'; ...
    };

LoopShapeAndMarginsRequirements = ...
    { ...
    'MinLoopGain'; ...
    'MaxLoopGain'; ...
    'LoopShape'; ...
    'Margins' ...
    };

PassivityAndSectorBoundsRequirements = ...
    { ...
    'Passivity';...
    'ConicSector';...
    'WeightedPassivity'; ...
    };
        
SystemDynamicsRequirements = ...
    { ....
    'Poles'; ...
    'StableController' ...
    };

switch GroupName
    case 'quickstart'
        List = QuickStart;
    case 'time'
        List = TimeDomainRequirements;
    case 'frequency'
        List = FrequencyDomainRequirements;
    case 'openloop'
        List = LoopShapeAndMarginsRequirements;
    case 'passivity'
        List = PassivityAndSectorBoundsRequirements;
    case 'systemdynamics'
        List = SystemDynamicsRequirements;
    otherwise
        List = vertcat( ...
                       QuickStart, ...
                       TimeDomainRequirements, ...
                       FrequencyDomainRequirements, ...
                       LoopShapeAndMarginsRequirements, ...
                       PassivityAndSectorBoundsRequirements, ...
                       SystemDynamicsRequirements ...
                       );
end